openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
  description: A simple API with a single ping endpoint.
paths:
  /ping:
    get:
      summary: Ping the server
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: pong